version: "3"

vars:
  COMPOSE_FILE: docker-compose.yml

tasks:
  git-pull:
    desc: Pulls up-to-date source code.
    cmds:
      - git pull

  compose-file:
    desc: Generates docker-compose file.
    vars:
      TEMPLATE_FILE: docker-compose-template.yml
      STACK_CONFIG: stack-config.toml
    deps:
      - git-pull
    cmds:
      - >
        docker run -i --rm --pull=always
        -v {{.TASKFILE_DIR}}/{{.STACK_CONFIG}}:/usr/src/{{.STACK_CONFIG}}:ro
        hairyhenderson/gomplate:stable
        --context stackConfig=/usr/src/{{.STACK_CONFIG}}
        < {{.TEMPLATE_FILE}}
        > {{.COMPOSE_FILE}}
    sources:
      - "{{.TEMPLATE_FILE}}"
      - "{{.STACK_CONFIG}}"
    generates:
      - "{{.COMPOSE_FILE}}"

  clean:
    desc: Removes generated files.
    cmds:
      - rm -f {{.COMPOSE_FILE}}
