[global]
checkNewVersion = false

[api]
insecure = true
dashboard = true

[entryPoints.http]
address = ":80"

[log]
level = "INFO"

[ping]

[providers.docker]
endpoint = "tcp://docker-proxy-reverse-proxy:2375"
exposedByDefault = false
